var assert = require('assert')
var game = require('./scrabble.js')
var success = require('./node_modules/success.js')

assert.strictEqual(game.scrabble("ladilmy", "daily"),true,'FAILED 1')
success()
assert.strictEqual(game.scrabble("eerriin", "eerie"),false,'FAILED 2')
success()
assert.strictEqual(game.scrabble("orrpgma", "program"),true,'FAILED 3')
success()
assert.strictEqual(game.scrabble("orppgma", "program"),false,'FAILED 4')
success('PASSED LEVEL 1')

assert.strictEqual(game.scrabble("pizza??", "pizzazz"),true,'FAILED 5')
success()
assert.strictEqual(game.scrabble("piizza?", "pizzazz"),false,'FAILED 6')
success()
assert.strictEqual(game.scrabble("a??????", "program"),true,'FAILED 7')
success()
assert.strictEqual(game.scrabble("b??????", "program"),false,'FAILED 8')
success('PASSED LEVEL 2')

// assert.strictEqual(game.longest("dcthoyueorza"),"coauthored",'FAILED 9')
// success()
// assert.strictEqual(game.longest("uruqrnytrois"),"turquois",'FAILED 10')
// success()
// assert.strictEqual(game.longest("rryqeiaegicgeo??"),"greengrocery",'FAILED 11')
// success()
// assert.strictEqual(game.longest("udosjanyuiuebr??"),"subordinately",'FAILED 12')
// success()
// assert.strictEqual(game.longest("vaakojeaietg????????"),"ovolactovegetarian",'FAILED 12')
// success()
// success('PASSED LEVEL 3')
//
// assert.strictEqual(game.longest("dcthoyueorza"),"zydeco",'FAILED 13')
// success()
// assert.strictEqual(game.longest("uruqrnytrois"),"squinty",'FAILED 14')
// success()
// assert.strictEqual(game.longest("rryqeiaegicgeo??"),"reacquiring",'FAILED 15')
// success()
// assert.strictEqual(game.longest("udosjanyuiuebr??"),"jaybirds",'FAILED 16')
// success()
// assert.strictEqual(game.longest("vaakojeaietg????????"),"straightjacketed",'FAILED 17')
// success()
// success('PASSED LEVEL 4')
